### ISSUE TITLE
Add visual feedback system for user interactions

### ISSUE THREAD

**Issue by kylesaldana5** [kylesaldana5/Animation-Rescue#20]
## Epic Reference
**Epic**: The First Rescue - MVP Core Experience  
**PRD Section**: UI Design - Visual Feedback for interactions  
**PRD Section**: Story 1.4 - Animate on Correct Answer

## Description
Create a comprehensive visual feedback system that provides immediate, clear, and engaging responses to all user interactions. This includes hover effects, click animations, loading states, and success/error feedback that enhances the game experience without overwhelming young learners.

## Implementation Steps
1. Create `src/components/VisualFeedback.tsx` for feedback components
2. Implement hover and focus states for all interactive elements
3. Add click/tap animations and ripple effects
4. Create loading spinners and progress indicators
5. Implement success celebrations and error gentle feedback
6. Add accessibility-compliant visual indicators
7. Create smooth transitions and micro-animations

## Files to Create/Modify
- `src/components/VisualFeedback.tsx` - Feedback component library
- `src/hooks/useVisualFeedback.ts` - Feedback management hook
- `src/styles/animations.css` - CSS animations and transitions
- `src/utils/feedbackHelpers.ts` - Feedback utility functions
- `src/components/CelebrationEffect.tsx` - Success celebration component

## Code Patterns
```typescript
// src/components/VisualFeedback.tsx
import { ReactNode, useState, useEffect } from 'react';

interface VisualFeedbackProps {
  children: ReactNode;
  type?: 'hover' | 'click' | 'success' | 'error' | 'loading';
  intensity?: 'subtle' | 'medium' | 'strong';
  disabled?: boolean;
  onClick?: () => void;
  className?: string;
}

export function VisualFeedback({
  children,
  type = 'hover',
  intensity = 'medium',
  disabled = false,
  onClick,
  className = ''
}: VisualFeedbackProps) {
  const [isActive, setIsActive] = useState(false);
  const [showRipple, setShowRipple] = useState(false);

  const getBaseStyles = () => {
    let styles = 'transition-all duration-200 ease-in-out ';
    
    if (disabled) {
      styles += 'opacity-60 cursor-not-allowed ';
      return styles + className;
    }

    // Hover effects
    if (type === 'hover' || type === 'click') {
      switch (intensity) {
        case 'subtle':
          styles += 'hover:scale-102 hover:shadow-sm ';
          break;
        case 'medium':
          styles += 'hover:scale-105 hover:shadow-md hover:brightness-110 ';
          break;
        case 'strong':
          styles += 'hover:scale-110 hover:shadow-lg hover:brightness-125 ';
          break;
      }
    }

    // Click effects
    if (type === 'click') {
      styles += 'active:scale-95 cursor-pointer ';
    }

    // Success styles
    if (type === 'success') {
      styles += 'bg-green-100 border-green-300 animate-pulse-green ';
    }

    // Error styles
    if (type === 'error') {
      styles += 'bg-orange-100 border-orange-300 animate-gentle-shake ';
    }

    // Loading styles
    if (type === 'loading') {
      styles += 'opacity-75 animate-pulse cursor-wait ';
    }

    return styles + className;
  };

  const handleClick = () => {
    if (disabled) return;
    
    if (type === 'click') {
      setShowRipple(true);
      setTimeout(() => setShowRipple(false), 300);
    }
    
    onClick?.();
  };

  return (
    <div 
      className={`relative ${getBaseStyles()}`}
      onClick={handleClick}
      onMouseEnter={() => setIsActive(true)}
      onMouseLeave={() => setIsActive(false)}
    >
      {children}
      
      {/* Ripple effect for clicks */}
      {showRipple && (
        <div className=\"absolute inset-0 rounded-inherit\">
          <div className=\"ripple-animation\" />
        </div>
      )}
      
      {/* Loading overlay */}
      {type === 'loading' && (
        <div className=\"absolute inset-0 flex items-center justify-center bg-white bg-opacity-50 rounded-inherit\">
          <div className=\"animate-spin w-6 h-6 border-2 border-blue-500 border-t-transparent rounded-full\" />
        </div>
      )}
    </div>
  );
}

// src/components/CelebrationEffect.tsx
interface CelebrationEffectProps {
  show: boolean;
  onComplete?: () => void;
  intensity?: 'small' | 'medium' | 'large';
}

export function CelebrationEffect({ 
  show, 
  onComplete, 
  intensity = 'medium' 
}: CelebrationEffectProps) {
  const [particles, setParticles] = useState<Array<{id: number, x: number, y: number, delay: number}>>([]);

  useEffect(() => {
    if (show) {
      // Generate random particles
      const particleCount = intensity === 'small' ? 10 : intensity === 'medium' ? 20 : 30;
      const newParticles = Array.from({ length: particleCount }, (_, i) => ({
        id: i,
        x: Math.random() * 100,
        y: Math.random() * 100,
        delay: Math.random() * 500
      }));
      
      setParticles(newParticles);
      
      // Auto-complete after animation
      setTimeout(() => {
        setParticles([]);
        onComplete?.();
      }, 2000);
    }
  }, [show, intensity, onComplete]);

  if (\!show) return null;

  return (
    <div className=\"fixed inset-0 pointer-events-none z-50 overflow-hidden\">
      {particles.map(particle => (
        <div
          key={particle.id}
          className=\"absolute animate-celebration-particle\"
          style={{
            left: `${particle.x}%`,
            top: `${particle.y}%`,
            animationDelay: `${particle.delay}ms`
          }}
        >
          {['🎉', '⭐', '🌟', '✨'][Math.floor(Math.random() * 4)]}
        </div>
      ))}
      
      {/* Center celebration text */}
      <div className=\"absolute inset-0 flex items-center justify-center\">
        <div className=\"animate-celebration-text text-6xl font-bold text-yellow-500 drop-shadow-lg\">
          ¡Excelente\!
        </div>
      </div>
    </div>
  );
}

// src/hooks/useVisualFeedback.ts
import { useState, useCallback } from 'react';

export function useVisualFeedback() {
  const [activeEffects, setActiveEffects] = useState<Set<string>>(new Set());

  const triggerEffect = useCallback((effectId: string, duration: number = 1000) => {
    setActiveEffects(prev => new Set(prev).add(effectId));
    
    setTimeout(() => {
      setActiveEffects(prev => {
        const newSet = new Set(prev);
        newSet.delete(effectId);
        return newSet;
      });
    }, duration);
  }, []);

  const isEffectActive = useCallback((effectId: string) => {
    return activeEffects.has(effectId);
  }, [activeEffects]);

  const clearAllEffects = useCallback(() => {
    setActiveEffects(new Set());
  }, []);

  return {
    triggerEffect,
    isEffectActive,
    clearAllEffects,
    activeEffectsCount: activeEffects.size
  };
}
```

## CSS Animations (add to src/styles/animations.css)
```css
/* Gentle animations for children */
@keyframes gentle-shake {
  0%, 100% { transform: translateX(0); }
  25% { transform: translateX(-3px); }
  75% { transform: translateX(3px); }
}

@keyframes pulse-green {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.8; }
}

@keyframes celebration-particle {
  0% {
    transform: translateY(0) scale(0);
    opacity: 1;
  }
  50% {
    transform: translateY(-100px) scale(1);
    opacity: 1;
  }
  100% {
    transform: translateY(-200px) scale(0);
    opacity: 0;
  }
}

@keyframes celebration-text {
  0% {
    transform: scale(0) rotate(-10deg);
    opacity: 0;
  }
  50% {
    transform: scale(1.2) rotate(5deg);
    opacity: 1;
  }
  100% {
    transform: scale(1) rotate(0deg);
    opacity: 1;
  }
}

.ripple-animation {
  position: absolute;
  inset: 0;
  border-radius: inherit;
  background: radial-gradient(circle, rgba(99, 102, 241, 0.3) 0%, transparent 70%);
  animation: ripple 0.3s ease-out;
}

@keyframes ripple {
  0% {
    transform: scale(0);
    opacity: 1;
  }
  100% {
    transform: scale(1);
    opacity: 0;
  }
}

/* Hover scale utilities */
.hover\\:scale-102:hover { transform: scale(1.02); }
.hover\\:scale-105:hover { transform: scale(1.05); }
.hover\\:scale-110:hover { transform: scale(1.1); }

.animate-gentle-shake {
  animation: gentle-shake 0.5s ease-in-out;
}

.animate-pulse-green {
  animation: pulse-green 1s ease-in-out infinite;
}

.animate-celebration-particle {
  animation: celebration-particle 2s ease-out forwards;
}

.animate-celebration-text {
  animation: celebration-text 0.8s ease-out forwards;
}
```

## Acceptance Criteria
- [ ] All interactive elements provide clear visual feedback
- [ ] Hover states are immediately recognizable
- [ ] Click/tap animations feel responsive and satisfying
- [ ] Success celebrations are joyful but not overwhelming
- [ ] Error feedback is gentle and encouraging
- [ ] Loading states clearly indicate system activity
- [ ] All animations are smooth and performant

## Technical Notes
- Use CSS transforms instead of layout changes for better performance
- Keep animations short and snappy for responsiveness
- Ensure accessibility compliance (respect prefers-reduced-motion)
- Design feedback to be encouraging rather than punitive

## Dependencies
- Depends on #14 (Create Answer choices component)
- Depends on #15 (Implement answer validation logic)

## Testing Requirements
- Visual feedback displays correctly across different devices
- Animations are smooth and don't cause performance issues
- Accessibility settings are respected
- Feedback enhances rather than distracts from learning
- All interactive states are clearly distinguishable
